from PyQt5 import QtCore, QtGui, QtWidgets

class OrganizationsChoiceDialog(object):
    def __init__(self):
        super().__init__()
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 450)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.acceptButtons = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptButtons.setOrientation(QtCore.Qt.Vertical)
        self.acceptButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.acceptButtons.setObjectName("acceptButtons")
        self.gridLayout.addWidget(self.acceptButtons, 1, 1, 1, 1)
        self.listOfFoundedCompanies = QtWidgets.QListView(Dialog)
        self.listOfFoundedCompanies.setObjectName("listOfFoundedCompanies")
        self.gridLayout.addWidget(self.listOfFoundedCompanies, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.acceptButtons.accepted.connect(Dialog.accept)
        self.acceptButtons.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 450)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.acceptButtons = QtWidgets.QDialogButtonBox(Dialog)
        self.acceptButtons.setOrientation(QtCore.Qt.Vertical)
        self.acceptButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptButtons.setObjectName("acceptButtons")
        self.gridLayout.addWidget(self.acceptButtons, 1, 1, 1, 1)
        self.listOfFoundedCompanies = QtWidgets.QListView(Dialog)
        self.listOfFoundedCompanies.setObjectName("listOfFoundedCompanies")
        self.gridLayout.addWidget(self.listOfFoundedCompanies, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.acceptButtons.accepted.connect(Dialog.accept)
        self.acceptButtons.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Выберите организации, по которым требуется сделать отчёты:"))